# -- Main Menu --
# Chinese AI Application Development Association (CAIADA) Main Menu Configuration

[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About Us"
  pageRef = "/about/"
  weight = 20

[[main]]
  name = "Association Charter"
  pageRef = "/about/charter/"
  weight = 30

[[main]]
  name = "News"
  pageRef = "/news/"
  weight = 40

[[main]]
  name = "Membership"
  pageRef = "/membership/"
  weight = 60

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "About Us"
  pageRef = "/about/"
  weight = 10

[[footer]]
  name = "Association Charter"
  pageRef = "/about/charter/"
  weight = 20